export const MAIN_PAGE_ROUTE = '/'
export const NOT_FOUND_ROUTE = '*'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const PROFILE_ROUTE = '/profile'
export const HOTEL_PAGE_ROUTE = '/Hotel_Page'
export const HOTEL_ROUTE = 'hotel'
